[package]
name = "kcshot-rs"
version = "0.1.0"
authors = ["Mițca Dumitru <dumitru0mitca@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.14.3"
once_cell = "1.2.0"
chrono = "0.4.19"
libc = "0.2.104"
x11 = "2.19"
cairo-rs = { version = "0.14.9", features = ["png", "xlib", "xcb"] }
tracing = "0.1.23"
tracing-subscriber = "0.2.15"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3.20"
