[package]
name = "kcshot-rs"
version = "0.1.0"
authors = ["Mițca Dumitru <dumitru0mitca@gmail.com>"]
edition = "2021"
license = "EUPL v1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# UI-related dependencies
ashpd = { version = "0.2.1", features = ["log", "feature_gtk4"] }
cairo-rs = { version = "0.15.1", features = ["png", "xcb"] }
pangocairo = "0.15.1"
image = { version = "0.24.0", default-features = false, features = ["png"] }
gtk4 = "0.4.1"
xcb = { git = "https://github.com/RealKC/rust-xcb", branch = "meta-attrs-atoms-of-struct", features = [
    "debug_atom_names",
    "shape",
] }
x11 = { version = "2.19", features = ["xlib"] }
ksni = "0.2.0"

# User settings, history
diesel = { version = "1.4.8", features = ["sqlite"] }
diesel_migrations = "1.4.0"
xdg = "2.1"

# Miscelaneous
once_cell = "1.2.0"
chrono = "0.4.19"
rand = "0.8.4"
libc = "0.2.104"

# Logging and error reporting
tracing = "0.1.23"
tracing-subscriber = "0.3.5"
thiserror = "1.0.30"

[build-dependencies]
gio = "0.15.1"

[features]
xdg-paths = []
